// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientApi.Admin
{
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Topics.
    /// </summary>
    public static partial class TopicsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// </param>
            public static object GetTopics(this ITopics operations, string tenantId)
            {
                return operations.GetTopicsAsync(tenantId).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetTopicsAsync(this ITopics operations, string tenantId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetTopicsWithHttpMessagesAsync(tenantId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// </param>
            /// <param name='topicName'>
            /// </param>
            public static string CreateTopic(this ITopics operations, string tenantId, string topicName)
            {
                return operations.CreateTopicAsync(tenantId, topicName).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// </param>
            /// <param name='topicName'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> CreateTopicAsync(this ITopics operations, string tenantId, string topicName, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateTopicWithHttpMessagesAsync(tenantId, topicName, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// </param>
            /// <param name='topicName'>
            /// </param>
            public static string DeleteTopic(this ITopics operations, string tenantId, string topicName)
            {
                return operations.DeleteTopicAsync(tenantId, topicName).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// </param>
            /// <param name='topicName'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> DeleteTopicAsync(this ITopics operations, string tenantId, string topicName, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DeleteTopicWithHttpMessagesAsync(tenantId, topicName, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// </param>
            public static string ResetKeys(this ITopics operations, string tenantId)
            {
                return operations.ResetKeysAsync(tenantId).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> ResetKeysAsync(this ITopics operations, string tenantId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ResetKeysWithHttpMessagesAsync(tenantId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
